### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by tdeneau** [aurbroszniowski/Rainfall-ehcache#4]
I got the following when trying to run "mvn clean"

[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.rainfall:rainfall-ehcache:1.0.2-SNAPSHOT (/home/tom/Rainfall-ehcache/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find io.rainfall:rainfall:pom:1.0.2-SNAPSHOT in http://snapshots.terracotta.org was cached in the local repository, resolution will not be reattempted until the update interval of terracotta-snapshots has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 7, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by aurbroszniowski** [comment]
The issue comes from the fact that the ehcache snapshot dependency is not publicly available.
You need to change the dependency version in the pom

change
```
   <dependency>
      <groupId>org.ehcache</groupId>
      <artifactId>ehcache</artifactId>
      <version>3.0.0-SNAPSHOT</version>
      <scope>provided</scope>
    </dependency>
```

into

```
   <dependency>
      <groupId>org.ehcache</groupId>
      <artifactId>ehcache</artifactId>
      <version>3.0.0.Alpha</version>
      <scope>provided</scope>
    </dependency>
```
